//! Cleanup candidates.
//!
//! Two kinds of rule, kept strictly apart because the consequences differ.
//!
//! `Safety::Safe` covers data an application regenerates on its own: caches,
//! build products, logs. Losing it costs time, never work, so these groups are
//! selected by default.
//!
//! `Safety::Review` covers the user's own files. A 40 GB video untouched for
//! two years is worth looking at, but only a person can say whether it goes.
//! These groups are never selected by default and never will be.
//!
//! Nothing here deletes. It produces a list; the caller sends it through the
//! same Trash confirmation as any other delete.

use std::collections::HashSet;

use serde::{Deserialize, Serialize};


use crate::index::files::DAY;
use crate::index::{ScanIndex, NO_PARENT};
use crate::model::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Safety {
    /// Regenerated by the application that wrote it.
    Safe,
    /// The user's own files. Listed, never pre-selected.
    Review,
}

enum Kind {
    /// The immediate children of each of these directories, relative to $HOME.
    ChildrenOf(&'static [&'static str]),
    /// Files at least `bytes` and untouched for at least `days`.
    LargeUnused { bytes: u64, days: f64 },
    /// Files under a directory, untouched for at least `days`.
    UnusedIn { dir: &'static str, days: f64 },
    /// Files with one of these extensions, untouched for at least `days`.
    UnusedExt {
        exts: &'static [&'static str],
        days: f64,
    },
}

struct Rule {
    id: &'static str,
    safety: Safety,
    kind: Kind,
}

/// Order matters: an item is claimed by the first rule that matches it, so the
/// specific directories come before the general ones.
const RULES: &[Rule] = &[
    Rule {
        id: "xcode",
        safety: Safety::Safe,
        kind: Kind::ChildrenOf(&[
            "Library/Developer/Xcode/DerivedData",
            "Library/Developer/Xcode/iOS DeviceSupport",
            "Library/Developer/Xcode/watchOS DeviceSupport",
            "Library/Developer/Xcode/tvOS DeviceSupport",
            "Library/Developer/CoreSimulator/Caches",
        ]),
    },
    Rule {
        id: "packageManagers",
        safety: Safety::Safe,
        kind: Kind::ChildrenOf(&[
            ".npm/_cacache",
            ".cache",
            ".gradle/caches",
            ".cargo/registry/cache",
            ".pnpm-store",
            "Library/Caches/Homebrew",
            "Library/Caches/pip",
            "Library/Caches/Yarn",
            "Library/Caches/go-build",
            "Library/Caches/ms-playwright",
        ]),
    },
    Rule {
        id: "appCaches",
        safety: Safety::Safe,
        kind: Kind::ChildrenOf(&["Library/Caches"]),
    },
    Rule {
        id: "logs",
        safety: Safety::Safe,
        kind: Kind::ChildrenOf(&["Library/Logs"]),
    },
    Rule {
        id: "largeUnused",
        safety: Safety::Review,
        kind: Kind::LargeUnused {
            bytes: 5 * 1024 * 1024 * 1024,
            days: 365.0,
        },
    },
    Rule {
        id: "oldDownloads",
        safety: Safety::Review,
        kind: Kind::UnusedIn {
            dir: "Downloads",
            days: 180.0,
        },
    },
    Rule {
        id: "installers",
        safety: Safety::Review,
        kind: Kind::UnusedExt {
            exts: &["dmg", "pkg", "xip", "iso"],
            days: 90.0,
        },
    },
];

/// Cap per group, so one pathological folder cannot produce a list nobody can
/// review or a Trash operation that runs for minutes.
const MAX_ITEMS: usize = 4000;

pub struct Group {
    pub id: &'static str,
    pub safety: Safety,
    pub items: Vec<ItemRef>,
    pub size: u64,
    pub files: u64,
    pub truncated: bool,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupSummary {
    pub id: String,
    pub safety: Safety,
    /// Top-level entries that would be moved.
    pub items: usize,
    /// Files below them, for context.
    pub files: u64,
    pub size: u64,
    pub truncated: bool,
}

impl Group {
    pub fn summary(&self) -> GroupSummary {
        GroupSummary {
            id: self.id.to_string(),
            safety: self.safety,
            items: self.items.len(),
            files: self.files,
            size: self.size,
            truncated: self.truncated,
        }
    }
}

/// Resolve a path to a directory id by walking the tree from the scan root.
fn find_dir(ix: &ScanIndex, path: &str) -> Option<u32> {
    let root = ix.root_path.trim_end_matches('/');
    let rest = if root.is_empty() {
        path.strip_prefix('/')?
    } else {
        path.strip_prefix(root)?.trim_start_matches('/')
    };

    let mut cur = 0u32;
    for part in rest.split('/').filter(|p| !p.is_empty()) {
        let next = ix.dirs[cur as usize]
            .children
            .iter()
            .copied()
            .find(|&c| ix.dir_name(c) == part)?;
        cur = next;
    }
    Some(cur)
}

fn dir_is_claimed(ix: &ScanIndex, mut dir: u32, claimed: &HashSet<u32>) -> bool {
    loop {
        if claimed.contains(&dir) {
            return true;
        }
        let parent = ix.dirs[dir as usize].parent;
        if parent == NO_PARENT {
            return false;
        }
        dir = parent;
    }
}

/// Evaluate every rule against the index.
pub fn evaluate(ix: &ScanIndex, home: &str, now: i64) -> Vec<Group> {
    let mut claimed: HashSet<u32> = HashSet::new();
    let mut out: Vec<Group> = Vec::new();

    for rule in RULES {
        let mut items: Vec<ItemRef> = Vec::new();
        let mut size = 0u64;
        let mut files = 0u64;
        let mut truncated = false;

        match &rule.kind {
            Kind::ChildrenOf(paths) => {
                for rel in *paths {
                    let full = format!("{}/{}", home.trim_end_matches('/'), rel);
                    let Some(dir) = find_dir(ix, &full) else { continue };
                    if dir == 0 || dir_is_claimed(ix, dir, &claimed) {
                        continue;
                    }
                    let d = &ix.dirs[dir as usize];
                    for &child in &d.children {
                        if items.len() >= MAX_ITEMS {
                            truncated = true;
                            break;
                        }
                        let c = &ix.dirs[child as usize];
                        if c.agg_alloc == 0 && c.agg_size == 0 {
                            continue;
                        }
                        if c.has(flags::IS_SYSTEM) || is_immutable_path(&ix.dir_path(child)) {
                            continue;
                        }
                        claimed.insert(child);
                        items.push(ItemRef {
                            id: child,
                            is_dir: true,
                        });
                        size += c.agg_alloc.max(c.agg_size);
                        files += c.agg_files;
                    }
                    for &fid in &d.files {
                        if items.len() >= MAX_ITEMS {
                            truncated = true;
                            break;
                        }
                        let f = &ix.files[fid as usize];
                        let bytes = f.alloc.max(f.size);
                        if bytes == 0 {
                            continue;
                        }
                        items.push(ItemRef {
                            id: fid,
                            is_dir: false,
                        });
                        size += bytes;
                        files += 1;
                    }
                }
            }

            Kind::LargeUnused { bytes, days } => {
                for &id in ix.items(true) {
                    if items.len() >= MAX_ITEMS {
                        truncated = true;
                        break;
                    }
                    let f = &ix.files[id as usize];
                    if f.alloc.max(f.size) < *bytes {
                        break; // `items` is size-descending
                    }
                    if !idle_at_least(f, now, *days) || dir_is_claimed(ix, f.parent, &claimed) {
                        continue;
                    }
                    if f.has(flags::IS_SYSTEM) || is_protected_path(&ix.item_path(id)) {
                        continue;
                    }
                    items.push(ItemRef { id, is_dir: false });
                    size += f.alloc.max(f.size);
                    files += 1;
                }
            }

            Kind::UnusedIn { dir, days } => {
                let full = format!("{}/{}", home.trim_end_matches('/'), dir);
                if let Some(root) = find_dir(ix, &full) {
                    let mut stack = vec![root];
                    while let Some(d) = stack.pop() {
                        for &fid in &ix.dirs[d as usize].files {
                            if items.len() >= MAX_ITEMS {
                                truncated = true;
                                break;
                            }
                            let f = &ix.files[fid as usize];
                            let bytes = f.alloc.max(f.size);
                            if bytes == 0 || f.has(flags::IS_SYSTEM) || !idle_at_least(f, now, *days)
                            {
                                continue;
                            }
                            if dir_is_claimed(ix, f.parent, &claimed) {
                                continue;
                            }
                            items.push(ItemRef {
                                id: fid,
                                is_dir: false,
                            });
                            size += bytes;
                            files += 1;
                        }
                        stack.extend_from_slice(&ix.dirs[d as usize].children);
                    }
                }
            }

            Kind::UnusedExt { exts, days } => {
                for &id in ix.items(true) {
                    if items.len() >= MAX_ITEMS {
                        truncated = true;
                        break;
                    }
                    let f = &ix.files[id as usize];
                    if !exts.contains(&ix.ext_name(f.ext)) {
                        continue;
                    }
                    if !idle_at_least(f, now, *days) || dir_is_claimed(ix, f.parent, &claimed) {
                        continue;
                    }
                    if f.has(flags::IS_SYSTEM) || is_protected_path(&ix.item_path(id)) {
                        continue;
                    }
                    items.push(ItemRef { id, is_dir: false });
                    size += f.alloc.max(f.size);
                    files += 1;
                }
            }
        }

        if !items.is_empty() {
            out.push(Group {
                id: rule.id,
                safety: rule.safety,
                items,
                size,
                files,
                truncated,
            });
        }
    }

    out
}

fn idle_at_least(f: &FileRec, now: i64, days: f64) -> bool {
    let last = f.effective_last_used();
    if last == NO_TIME {
        // Unknown usage never counts as "long unused".
        return false;
    }
    ((now - last).max(0) as f64) / DAY as f64 >= days
}

#[cfg(test)]
mod tests {
    use super::*;

    fn build() -> (ScanIndex, String) {
        // <root>/Users/me/Library/Caches/SomeApp/blob.bin  (safe)
        // <root>/Users/me/Movies/huge.mov                  (review)
        // <root>/System/Library/big.bin                    (never)
        let mut ix = ScanIndex::new("/root".into(), "T".into());
        let mkdir = |ix: &mut ScanIndex, name: &str, parent: u32| {
            let n = ix.names.push(name);
            let depth = if parent == NO_PARENT {
                0
            } else {
                ix.dirs[parent as usize].depth + 1
            };
            let sys = name == "System";
            let mut f = flags::IS_DIR;
            if sys {
                f |= flags::IS_SYSTEM;
            }
            ix.dirs.push(DirRec::new(n, parent, depth, f));
            let id = ix.dirs.len() as u32 - 1;
            if parent != NO_PARENT {
                ix.dirs[parent as usize].children.push(id);
            }
            id
        };
        let root = mkdir(&mut ix, "/root", NO_PARENT);
        let users = mkdir(&mut ix, "Users", root);
        let me = mkdir(&mut ix, "me", users);
        let lib = mkdir(&mut ix, "Library", me);
        let caches = mkdir(&mut ix, "Caches", lib);
        let someapp = mkdir(&mut ix, "SomeApp", caches);
        let movies = mkdir(&mut ix, "Movies", me);
        let system = mkdir(&mut ix, "System", root);
        let syslib = mkdir(&mut ix, "Library", system);
        ix.dirs[syslib as usize].flags |= flags::IS_SYSTEM;

        let now = 1_800_000_000i64;
        let addfile = |ix: &mut ScanIndex, dir: u32, name: &str, size: u64, idle_days: i64| {
            // The scanner propagates IS_SYSTEM down from a protected parent.
            let inherited = ix.dirs[dir as usize].flags & flags::IS_SYSTEM;
            let ext = extension_of(name);
            let e = ix.intern_ext(&ext);
            let n = ix.names.push(name);
            ix.files.push(FileRec {
                name: n,
                parent: dir,
                ext: e,
                size,
                alloc: size,
                mtime: now - idle_days * DAY,
                atime: now - idle_days * DAY,
                btime: now - idle_days * DAY,
                last_used: now - idle_days * DAY,
                flags: inherited,
            });
            let id = ix.files.len() as u32 - 1;
            ix.dirs[dir as usize].files.push(id);
            id
        };
        let gb = 1024 * 1024 * 1024;
        addfile(&mut ix, someapp, "blob.bin", 2 * gb, 5);
        addfile(&mut ix, movies, "huge.mov", 9 * gb, 500);
        addfile(&mut ix, movies, "recent.mov", 9 * gb, 3);
        addfile(&mut ix, syslib, "big.bin", 8 * gb, 900);
        ix.finalize(now);
        (ix, "/root/Users/me".to_string())
    }

    #[test]
    fn finds_a_directory_by_path() {
        let (ix, _) = build();
        let d = find_dir(&ix, "/root/Users/me/Library/Caches").expect("Caches");
        assert_eq!(ix.dir_name(d), "Caches");
        assert!(find_dir(&ix, "/root/nope/nope").is_none());
        assert!(find_dir(&ix, "/elsewhere/Users").is_none());
    }

    #[test]
    fn caches_are_safe_and_user_files_are_review() {
        let (ix, home) = build();
        let groups = evaluate(&ix, &home, 1_800_000_000);

        let caches = groups.iter().find(|g| g.id == "appCaches").expect("appCaches");
        assert_eq!(caches.safety, Safety::Safe);
        assert_eq!(caches.items.len(), 1, "one per-app cache folder");
        assert!(caches.items[0].is_dir);
        assert_eq!(caches.size, 2 * 1024 * 1024 * 1024);

        let large = groups.iter().find(|g| g.id == "largeUnused").expect("largeUnused");
        assert_eq!(large.safety, Safety::Review);
        let names: Vec<&str> = large.items.iter().map(|i| ix.file_name(i.id)).collect();
        assert_eq!(names, vec!["huge.mov"], "recent.mov is fresh, big.bin is system");
    }

    #[test]
    fn system_paths_are_never_offered() {
        let (ix, home) = build();
        for g in evaluate(&ix, &home, 1_800_000_000) {
            for it in &g.items {
                let (p, sys) = if it.is_dir {
                    (ix.dir_path(it.id), ix.dirs[it.id as usize].has(flags::IS_SYSTEM))
                } else {
                    (ix.item_path(it.id), ix.files[it.id as usize].has(flags::IS_SYSTEM))
                };
                assert!(!sys, "{p} is flagged as system and must not be offered");
                assert!(!is_protected_path(&p), "{p} must not be offered");
                assert!(!is_immutable_path(&p), "{p} must not be offered");
            }
        }
    }

    #[test]
    fn an_item_belongs_to_one_group_only() {
        let (ix, home) = build();
        let groups = evaluate(&ix, &home, 1_800_000_000);
        let mut seen = HashSet::new();
        for g in &groups {
            for it in &g.items {
                assert!(
                    seen.insert((it.id, it.is_dir)),
                    "item counted twice, so the totals would lie"
                );
            }
        }
    }

    #[test]
    fn unknown_usage_is_not_treated_as_unused() {
        let (mut ix, home) = build();
        for f in ix.files.iter_mut() {
            f.last_used = NO_TIME;
            f.atime = NO_TIME;
        }
        let groups = evaluate(&ix, &home, 1_800_000_000);
        assert!(
            groups.iter().all(|g| g.id != "largeUnused"),
            "a file we know nothing about must not be called long-unused"
        );
    }
}
